name: Deploy local com agente GitHub Actions

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: self-hosted  # 👈 importante: define que é no seu PC

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Build e Publish
      run: dotnet publish -c Release -o publish

    - name: Deploy com Robocopy
      run: |
        robocopy publish "C:\inetpub\wwwroot\MonolitoModular" /MIR
